name: Deploy to jetty

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      server:
        required: true
        type: string
      instance:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B -Pprodtest package
      - name: Deploy to server
        run: ~/deploy .${{ inputs.file }} ${{ inputs.server }} ${{ inputs.instance }} ${{ inputs.context }}.war
